-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity hw2 is
  port (
    A: in std_logic;
    B: in std_logic;
    C: in std_logic;
    D: in std_logic;
    E: out std_logic);
end hw2;

architecture Behavioral of hw2 is
  signal s0: std_logic;
  signal s1: std_logic;
  signal s2: std_logic;
  signal s3: std_logic;
begin
  E <= ((NOT (A XOR B) AND (C XOR D)) OR (NOT (C XOR D) AND (A XOR B)));
  s0 <= NOT A;
  s1 <= NOT B;
  s2 <= NOT C;
  s3 <= NOT D;
end Behavioral;
