-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Fulladder4 is
    port(
        A  : in  std_logic_vector(3 downto 0);
        B  : in  std_logic_vector(3 downto 0);
        Ci : in  std_logic;
        S  : out std_logic_vector(3 downto 0)
    );
end Fulladder4;

architecture Structure of Fulladder4 is
    signal A_int, B_int, S_int : integer := 0;
begin

    A_int <= to_integer(unsigned(A));
    B_int <= to_integer(unsigned(B));

    S_int <= (A_int + B_int) when Ci = '0' else (A_int - B_int);

    S <= std_logic_vector(to_unsigned(S_int, 4));

end Structure;


LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity FullAdder4 is
  port (
    A: in std_logic_vector(3 downto 0);
    B: in std_logic_vector(3 downto 0);
    Ci: in std_logic;
    s: out std_logic_vector(3 downto 0));
end main;

architecture Behavioral of main is
begin
  gate0: entity work.FullAdder4 -- FullAdder4
    port map (
      A => A,
      B => B,
      Ci => Ci,
      S => s);
end Behavioral;
